# GraphQL queries
query getLocation($locationName: String!) {
  Location(name: $locationName) {
    id,
    name,
    lastUpdated,
    subjects(orderBy: sequence_ASC) {
      id,
      name,
      score,
      image,
      slider
      factors(orderBy: createdAt_ASC) {
        id,
        description,
        score
      }
    }
  }
}