# GraphQL queries
query getLocation($locationName: String!, $startDate:DateTime!, $endDate:DateTime!, $endNull:DateTime) {
  Location(name: $locationName) {
    id,
    name,
    lastUpdated,
    subjects(orderBy: sequence_ASC) {
      id,
      name,
      score,
      image,
      weight,
      slider
      factors(orderBy: createdAt_DESC, filter:{
    AND: [{
      startOn_lte:$startDate,
      OR:[{
        endOn: $endNull
      },{
        endOn_lte: $endDate
      }]
    }]
      }) {
        id,
        description,
        score,
        startOn,
        endOn
      }
    }
  }
}